/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static Controle.CadastroControle.obterTodos;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Junior
 */
public class TelaPrestador extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrestador
     */
    public TelaPrestador() {
        initComponents();
        
    }
public static void obterTarefas(DefaultTableModel modeloTab) throws SQLException, ClassNotFoundException {
        modeloTab.setNumRows(0);
        List<Object[]> cadastro = obterTodos();
        for (Object[] t : cadastro){
            modeloTab.addRow( t);  
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cnpjtxt = new javax.swing.JTextField();
        cadastrarbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nometxt = new javax.swing.JTextField();
        funcaotxt = new javax.swing.JTextField();
        enderecotxt = new javax.swing.JTextField();
        uftxt = new javax.swing.JTextField();
        telefonetxt = new javax.swing.JTextField();
        estadociviltxt = new javax.swing.JTextField();
        tipodepixtxt = new javax.swing.JTextField();
        bancotxt = new javax.swing.JTextField();
        pixtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Salariotxt = new javax.swing.JTextField();
        atualizarbtn = new javax.swing.JButton();
        deletarbtn = new javax.swing.JButton();
        consultarbtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Tela Prestador");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdFuncionario", "Função", "UF", "CNPJ", "Telefone", "Pix", "TipoPix", "Banco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nome");

        cadastrarbtn.setText("Cadastrar");
        cadastrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("CNPJ");

        jLabel7.setText("Função");

        jLabel9.setText("UF");

        jLabel10.setText("Telefone");

        jLabel11.setText("Estado Civíl");

        jLabel12.setText("TIpo de Pix");

        jLabel13.setText("Pix");

        funcaotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcaotxtActionPerformed(evt);
            }
        });

        telefonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonetxtActionPerformed(evt);
            }
        });

        tipodepixtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodepixtxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Banco");

        jLabel8.setText("Endereço");

        jLabel14.setText("Salário");

        Salariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalariotxtActionPerformed(evt);
            }
        });

        atualizarbtn.setText("Atualizar");
        atualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarbtnActionPerformed(evt);
            }
        });

        deletarbtn.setText("Deletar");
        deletarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarbtnActionPerformed(evt);
            }
        });

        consultarbtn.setText("Consultar");
        consultarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbtnActionPerformed(evt);
            }
        });

        jLabel15.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cnpjtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(funcaotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(enderecotxt)
                                            .addComponent(uftxt)
                                            .addComponent(Salariotxt))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel10))
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bancotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(telefonetxt)
                                    .addComponent(estadociviltxt)
                                    .addComponent(tipodepixtxt)
                                    .addComponent(pixtxt))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarbtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deletarbtn)
                                        .addComponent(atualizarbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(consultarbtn)))))
                .addGap(92, 166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(consultarbtn)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(estadociviltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrarbtn)
                                .addGap(22, 22, 22)
                                .addComponent(atualizarbtn)
                                .addGap(26, 26, 26)
                                .addComponent(deletarbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(telefonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cnpjtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nometxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enderecotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(uftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Salariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tipodepixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(pixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addComponent(bancotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonetxtActionPerformed

    private void tipodepixtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodepixtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipodepixtxtActionPerformed

    private void SalariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalariotxtActionPerformed

    private void funcaotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcaotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcaotxtActionPerformed

    private void cadastrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbtnActionPerformed
                                             
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();

        if (nomeTarefaTxt.getText().isEmpty() | responsavelTxt.getText().isEmpty() | emailResponsavelTxt.getText().isEmpty()) {
            mensagemCadastroLbl.setText("Preencha os campos obrigatórios.");
        } else {
            try {
                trf.setNomeTarefa(nomeTarefaTxt.getText());
                trf.setCategoria(String.valueOf(categoriaCmb.getSelectedItem()));
                trf.setDescricao(descricaoTxt.getText());
                trf.setResponsavel(responsavelTxt.getText());
                trf.setEmailResponsavel(emailResponsavelTxt.getText());
                trf.setSetor(String.valueOf(setorCmb.getSelectedItem()));
                trf.setDataAbertura(dataAberturaTxt.getText());
                trf.setDataLimite(dataLimiteTxt.getText());
                trf.setStatus(String.valueOf(statusCmb.getSelectedItem()));
                trfDao.inserirTarefa(trf);
                mensagemCadastroLbl.setText("Cadastrado com sucesso.");
            } catch (ClassNotFoundException | SQLException ex) {
                mensagemCadastroLbl.setText("ERRO: " + ex.getMessage());
            }
        }
                  // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarbtnActionPerformed

    private void atualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarbtnActionPerformed
    mensagemConsultaLbl.setText("mensagem...");
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();
        //trf.setId(Integer.parseInt(idConsultaTxt.getText()));

        if (idConsultaTxt.getText().isEmpty()){
            mensagemConsultaLbl.setText("ID não preenchido");            
        } else {
            try {
                trf.setStatus(String.valueOf(atualizarCmb.getSelectedItem()));
                trf.setId(Integer.parseInt(idConsultaTxt.getText()));                
                trfDao.atualizar(trf);
                mensagemConsultaLbl.setText("Status da tarefa atualizado!");
            } catch (ClassNotFoundException | SQLException ex) {
                mensagemConsultaLbl.setText("ERRO: " + ex.getMessage());
            }
        }  
    }//GEN-LAST:event_atualizarbtnActionPerformed

    private void consultarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbtnActionPerformed
 mensagemConsultaLbl.setText("Mensagem...");
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();
        trf.setId(Integer.parseInt(idConsultaTxt.getText()));
        try {
            trf = trfDao.consultarById(trf);
            if (trf.getNomeTarefa() != null) {
                nomeConsultaTxt.setText(trf.getNomeTarefa());
                categoriaConsultaTxt.setText(trf.getCategoria());
                descricaoConsultaTxt.setText(trf.getDescricao());
                responsavelConsultaTxt.setText(trf.getResponsavel());
                emailResponsavelConsultaTxt.setText(trf.getEmailResponsavel());
                setorConsultaTxt.setText(trf.getSetor());
                dataAberturaConsultaTxt.setText(trf.getDataAbertura());
                dataLimiteConsultaTxt.setText(trf.getDataLimite());
                statusConsultaTxt.setText(trf.getStatus());

                mensagemConsultaLbl.setText("Tarefa encontradas!");
            } else {
                mensagemConsultaLbl.setText("Tarefa não encontrada!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemConsultaLbl.setText("Erro" + ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_consultarbtnActionPerformed

    private void deletarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarbtnActionPerformed
String[] dados = new String[5];
        int linhaselecionada = -1;
        linhaselecionada = tabelaTarefas.getSelectedRow();
       try{
        if(linhaselecionada >= 0){
            //nomeTarefa.setText((String)tabelaTarefas.getValueAt(linhaselecionada,0));
            dados[0] = (tabelaTarefas.getValueAt(linhaselecionada, 0)).toString();
        
            controller.TarefaControle.deletarId(dados);
            JOptionPane.showMessageDialog(this,"Deletado ocm sucesso!");
            ((DefaultTableModel)tabelaTarefas.getModel()).removeRow(linhaselecionada);
            
        }else JOptionPane.showMessageDialog(this, "É necessário selecionar uma linha");
       } catch (SQLException | ClassNotFoundException ex) {
           System.out.println("ERROR" + ex.getMessage());
       }
        
        

    }//GEN-LAST:event_deletarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrestador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrestador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Salariotxt;
    private javax.swing.JButton atualizarbtn;
    private javax.swing.JTextField bancotxt;
    private javax.swing.JButton cadastrarbtn;
    private javax.swing.JTextField cnpjtxt;
    private javax.swing.JButton consultarbtn;
    private javax.swing.JButton deletarbtn;
    private javax.swing.JTextField enderecotxt;
    private javax.swing.JTextField estadociviltxt;
    private javax.swing.JTextField funcaotxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nometxt;
    private javax.swing.JTextField pixtxt;
    private javax.swing.JTextField telefonetxt;
    private javax.swing.JTextField tipodepixtxt;
    private javax.swing.JTextField uftxt;
    // End of variables declaration//GEN-END:variables
}
